---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-kubernets
spec:
  selector:
    matchLabels:
      app: springboot-docker-kubernets
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-docker-kubernets
    spec:
      containers:
        - name: springboot-docker-kubernets
          image: tusharjadhav2386/dockertesting1:springboot-docker-kubernets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-kubernets
spec:
  selector:
    app: springboot-docker-kubernets
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer
