apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: springboot-docker-kubernets
spec:
  selector:
    matchLabels:
      app: springboot-docker-kubernets
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springboot-docker-kubernets
    spec:
      containers:
        - name: springboot-docker-kubernets
          image: tusharjadhav2386/dockertesting1:springboot-docker-kubernets # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster