apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-kubernets
spec:
  selector:
    app: springboot-docker-kubernets
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer